---

- hosts: "{{ target }}"
  remote_user: ubuntu
  become: true
  gather_facts: yes
  roles:
    - role: greendayonfire.mongodb
      when: "'mongo_master' in group_names"


- name: "Provision a Docker Swarm cluster"
  hosts: docker_engine
  remote_user: ubuntu
  become: true
  gather_facts: yes
  roles:
    - role: atosatto.docker-swarm